"""Add due_date column to Loan model

Revision ID: 053765e92c65
Revises: 
Create Date: 2023-10-07 01:03:27.023767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053765e92c65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
